// Generated by tools/build-basemap.py — do not edit.
//
// The digest of data/basemap.bin at the commit that shipped it. lib/Basemap.js
// stamps this into the decoded cache and refuses a cache stamped with anything
// else, so rebuilding the basemap invalidates every cached decode without a
// version anybody has to remember to bump. test/basemap.test.js holds this to
// the file in the tree.

.pragma library

var BASEMAP_SHA256 = "4c07b8a01016b54ae81648126fe6bde81c40020974ad99cf3f39366c7051d3d4"
